name: Sync Upstream Repository

on:
  schedule:
    - cron: '0 0 * * *' # 每天凌晨 0 点运行
  workflow_dispatch: # 手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    # Step 1: 检查出目标仓库代码
    - name: Checkout Target Repository
      uses: actions/checkout@v3
      with:
        ref: master # 替换为你的默认分支名称（此处为 master）

    # Step 2: 添加上游仓库为远程
    - name: Add Upstream Repository
      run: |
        git remote add upstream https://github.com/qist/tvbox.git
        git fetch upstream

    # Step 3: 同步上游代码并保留特定文件
    - name: Sync from Upstream
      run: |
        # 备份指定文件
        mkdir -p /tmp/backup
        cp CNAME /tmp/backup/CNAME || true
        cp -r .github/workflows /tmp/backup/workflows || true

        # 合并上游分支
        git merge upstream/master --allow-unrelated-histories -X theirs -m "Merge from upstream"

        # 恢复备份的文件
        cp /tmp/backup/CNAME CNAME || true
        cp -r /tmp/backup/workflows .github/workflows || true

        # 标记文件为已更新
        git add CNAME .github/workflows

    # Step 4: 提交并推送更改
    - name: Commit and Push Changes
      run: |
        git config user.name "justn-gpt"
        git config user.email "146205844+justn-gpt@users.noreply.github.com"

        git commit -m "Sync with upstream, retain CNAME and workflows" || echo "No changes to commit"
        git push origin master
