name: Sync Upstream Repository

on:
  schedule:
    - cron: '0 0 * * *' # 每天凌晨运行一次
  workflow_dispatch: # 手动触发工作流

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    # Step 1: 检查出你的仓库代码
    - name: Checkout Target Repository
      uses: actions/checkout@v3
      with:
        ref: main # 替换为你的默认分支名称（如 `master`）

    # Step 2: 添加上游仓库为远程分支
    - name: Add Upstream Repository
      run: |
        git remote add upstream https://github.com/上游仓库的用户名/上游仓库名.git
        git fetch upstream

    # Step 3: 拉取上游代码，但保留特定文件
    - name: Sync from Upstream
      run: |
        # 备份 CNAME 和 workflows 目录
        cp CNAME /tmp/CNAME || true
        cp -r .github/workflows /tmp/workflows || true

        # 合并上游分支的内容
        git merge upstream/main --allow-unrelated-histories -X theirs -m "Merge from upstream"

        # 恢复 CNAME 和 workflows 文件夹
        cp /tmp/CNAME CNAME || true
        cp -r /tmp/workflows .github/workflows || true

        # 添加文件到提交
        git add CNAME .github/workflows

    # Step 4: 提交和推送更改
    - name: Commit and Push Changes
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

        git commit -m "Sync with upstream, retain CNAME and workflows" || echo "No changes to commit"
        git push origin main
