name: Sync Upstream Repository

on:
  schedule:
    - cron: '0 0 * * *' # 每天凌晨 0 点运行
  workflow_dispatch: # 手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Target Repository
      uses: actions/checkout@v3
      with:
        ref: master # 替换为你的默认分支名称（此处为 master）

    - name: Configure Git User
      run: |
        git config user.name "justn-gpt"
        git config user.email "146205844+justn-gpt@users.noreply.github.com"

    - name: Add Upstream Repository
      run: |
        if git remote | grep -q '^upstream$'; then
          echo "Upstream remote already exists."
        else
          git remote add upstream https://github.com/qist/tvbox.git
        fi
        git fetch upstream

    - name: Check for Upstream Updates
      id: check-updates
      run: |
        UPSTREAM_HASH=$(git rev-parse upstream/master)
        BASE_HASH=$(git merge-base upstream/master master)
        if [ "$UPSTREAM_HASH" = "$BASE_HASH" ]; then
          echo "No updates from upstream."
          echo "has_updates=false" >> $GITHUB_ENV
        else
          echo "Updates detected from upstream."
          echo "has_updates=true" >> $GITHUB_ENV
        fi

    - name: Sync from Upstream
      if: env.has_updates == 'true'
      run: |
        mkdir -p /tmp/backup
        cp CNAME /tmp/backup/CNAME || true
        cp -r .github/workflows /tmp/backup/workflows || true
        git merge upstream/master --allow-unrelated-histories -X theirs -m "Merge from upstream"
        cp /tmp/backup/CNAME CNAME || true
        cp -r /tmp/backup/workflows .github/workflows || true
        git add CNAME .github/workflows

    - name: Commit and Push Changes
      if: env.has_updates == 'true'
      run: |
        git commit -m "Sync with upstream, retain CNAME and workflows" || echo "No changes to commit"
        git push origin master
