name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 17 * * *'  # 每天凌晨北京时间1:00 自动运行
  workflow_dispatch:      # 也可以手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # 获取完整历史记录避免浅克隆问题
          ref: master  # 使用 master 分支

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream repository
        run: |
          git remote add upstream https://github.com/qist/tvbox.git
          git fetch upstream

      - name: Fetch and merge upstream changes
        run: |
          git fetch upstream
          git merge upstream/master --no-edit  # 合并上游更改

      - name: Push changes
        run: |
          git push origin master  # 推送到 master 分支
